# Generated by Django 5.2.4 on 2026-04-29 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('TOKEN_REFRESH', 'Token refresh'), ('USER_CREATE', 'User create'), ('USER_UPDATE', 'User update'), ('USER_UPDATE_ROLE', 'User update role'), ('USER_DELETE', 'User delete'), ('USER_RESTORE', 'User restore'), ('PRODUCT_CREATE', 'Product create'), ('PRODUCT_UPDATE', 'Product update'), ('PRODUCT_DELETE', 'Product delete'), ('PRODUCT_RESTORE', 'Product restore')], max_length=40)),
                ('entity_type', models.CharField(choices=[('AUTH', 'Auth'), ('USER', 'User'), ('PRODUCT', 'Product')], max_length=40)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_email'], name='audit_logs_actor_e_f3ef0d_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['entity_type'], name='audit_logs_entity__4f758f_idx'), models.Index(fields=['status'], name='audit_logs_status_515e02_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
