# Generated by Django 5.2.4 on 2026-04-29 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("DIGITAL", "Digital"),
                            ("SERVICE", "Service"),
                        ],
                        default="PHYSICAL",
                        max_length=20,
                    ),
                ),
                ("product_key", models.CharField(max_length=20, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image_link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="products_name_6f9890_idx"),
                    models.Index(
                        fields=["product_key"], name="products_product_930a35_idx"
                    ),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="products_is_acti_dc210d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="products_created_e1ba5f_idx"
                    ),
                ],
            },
        ),
    ]
